development:
  adapter: postgresql
  encoding: unicode
  database: gem
  pool: 2
  username: buck
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: gem
#   pool: 2
#   username: your_username
#   password: your_password
